#ifndef VSENSE_CONFIG_H
#define VSENSE_CONFIG_H

#include "sdkconfig.h"

#define VSENSE_NODE_ID              CONFIG_VSENSE_NODE_ID

#if CONFIG_VSENSE_NODE_ROLE_TX
#define VSENSE_NODE_ROLE            "TX"
#elif CONFIG_VSENSE_NODE_ROLE_RX
#define VSENSE_NODE_ROLE            "RX"
#else
#error "A VSense node role must be selected."
#endif

#define VSENSE_WIFI_CHANNEL         CONFIG_VSENSE_WIFI_CHANNEL
#define VSENSE_WIFI_BSSID_LOCK_ENABLED \
    CONFIG_VSENSE_WIFI_BSSID_LOCK_ENABLED
#if CONFIG_VSENSE_WIFI_BSSID_LOCK_ENABLED
#define VSENSE_WIFI_BSSID           CONFIG_VSENSE_WIFI_BSSID
#endif
#define VSENSE_PACKET_RATE_HZ       CONFIG_VSENSE_PACKET_RATE_HZ
#define VSENSE_HEALTH_INTERVAL_MS   CONFIG_VSENSE_HEALTH_INTERVAL_MS
#define VSENSE_WIFI_SSID            CONFIG_VSENSE_WIFI_SSID
#define VSENSE_WIFI_PASSWORD        CONFIG_VSENSE_WIFI_PASSWORD
#define VSENSE_MQTT_KEEPALIVE_SECONDS \
    CONFIG_VSENSE_MQTT_KEEPALIVE_SECONDS

#define VSENSE_RX_UDP_PORT          CONFIG_VSENSE_RX_UDP_PORT
#define VSENSE_RX_01_IP             CONFIG_VSENSE_RX_01_IP
#define VSENSE_RX_02_ENABLED        CONFIG_VSENSE_RX_02_ENABLED
#if CONFIG_VSENSE_RX_02_ENABLED
#define VSENSE_RX_02_IP             CONFIG_VSENSE_RX_02_IP
#endif
#define VSENSE_TX_TARGET_PORT       CONFIG_VSENSE_TX_TARGET_PORT

#define VSENSE_TX_MAC_FILTER_ENABLED \
    CONFIG_VSENSE_TX_MAC_FILTER_ENABLED
#define VSENSE_TX_MAC               CONFIG_VSENSE_TX_MAC

#define VSENSE_COLLECTOR_IP         CONFIG_VSENSE_COLLECTOR_IP
#define VSENSE_COLLECTOR_UDP_PORT   CONFIG_VSENSE_COLLECTOR_UDP_PORT

#define VSENSE_MQTT_BROKER_URI      CONFIG_VSENSE_MQTT_BROKER_URI
#define VSENSE_CSI_BUFFER_MAX_LEN   CONFIG_VSENSE_CSI_BUFFER_MAX_LEN
#define VSENSE_CSI_LENGTH_FILTER_ENABLED \
    CONFIG_VSENSE_CSI_LENGTH_FILTER_ENABLED
#if CONFIG_VSENSE_CSI_LENGTH_FILTER_ENABLED
#define VSENSE_CSI_EXPECTED_LEN     CONFIG_VSENSE_CSI_EXPECTED_LEN
#else
#define VSENSE_CSI_EXPECTED_LEN     0
#endif
#define VSENSE_RAW_SEND_EVERY_N_FRAMES \
    CONFIG_VSENSE_RAW_SEND_EVERY_N_FRAMES

#endif /* VSENSE_CONFIG_H */
